# Site settings
title: Kerno的备忘录 # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "风雨顺时，无病欢乐"  # 一句话描述你的博客
baseurl: ""
url: "https://kerno-yep.github.io/"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "kerno" # 填写作者信息：名字
  email: kerne1@foxmail.com # 填写作者信息：邮箱
  bio: "收藏从未开始，学习从未开始" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改


# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "kerno" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white
